import { Footer } from './(components)/footer';
import { NavBar } from './(components)/nav-bar';
import './styles/globals.scss';
import localFont from 'next/font/local';

const fjallaOne = localFont({
  src: './assets/fonts/FjallaOne-Regular.ttf',
  variable: '--font-fjallaOne',
});
const neueHaasUnica = localFont({
  src: [
    {
      path: './assets/fonts/NeueHaasUnicaPro-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './assets/fonts/NeueHaasUnicaPro-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-neueHaasUnica',
});

export const metadata = {
  title: 'RideRev',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`${fjallaOne.variable} ${neueHaasUnica.variable}`}
    >
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
